<?php

declare(strict_types=1);

namespace Yoti\IDV;

use Yoti\Constants;
use Yoti\Exception\PemFileException;
use Yoti\IDV\Session\Create\CreateSessionResult;
use Yoti\IDV\Session\Create\FaceCapture\CreateFaceCaptureResourcePayload;
use Yoti\IDV\Session\Create\FaceCapture\UploadFaceCaptureImagePayload;
use Yoti\IDV\Session\Create\SessionSpecification;
use Yoti\IDV\Session\Instructions\Instructions;
use Yoti\IDV\Session\Retrieve\Configuration\SessionConfigurationResponse;
use Yoti\IDV\Session\Retrieve\GetSessionResult;
use Yoti\IDV\Session\Retrieve\Instructions\ContactProfileResponse;
use Yoti\IDV\Session\Retrieve\Instructions\InstructionsResponse;
use Yoti\IDV\Support\SupportedDocumentsResponse;
use Yoti\Media\Media;
use Yoti\Util\Config;
use Yoti\Util\Env;
use Yoti\Util\PemFile;
use Yoti\Util\Validation;

/**
 * Client used for communication with the Yoti Doc Scan service,
 * where any signed request is required.
 * <p>
 * The {@code IDVClient} is to be used by clients to facilitate
 * requests to the Yoti Doc Scan system where any signed requests are
 * required.  Using the supplied models, clients can build requests
 * and perform the requests to the Doc Scan system.
 */
class IDVClient
{
    /**
     * @var Service
     */
    private $IDVService;

    /**
     * IDVClient constructor.
     *
     * @param string $sdkId
     *   The SDK identifier generated by Yoti Hub when you create your app.
     * @param string $pem
     *   PEM file path or string
     * @param array<string, mixed> $options (optional)
     *   SDK configuration options - {@see \Yoti\Util\Config} for available options.
     *
     * @throws PemFileException
     */
    public function __construct(
        string $sdkId,
        string $pem,
        array $options = []
    ) {
        Validation::notEmptyString($sdkId, 'SDK ID');
        $pemFile = PemFile::resolveFromString($pem);

        // Set API URL from environment variable.
        $options[Config::API_URL] = $options[Config::API_URL] ?? Env::get(Constants::ENV_DOC_SCAN_API_URL);

        $config = new Config($options);

        $this->IDVService = new Service($sdkId, $pemFile, $config);
    }

    /**
     * Creates a session within the Yoti Doc Scan session
     * using the supplied specification.
     *
     * @param SessionSpecification $sessionSpecification
     * @return CreateSessionResult
     * @throws Exception\IDVException
     */
    public function createSession(SessionSpecification $sessionSpecification): CreateSessionResult
    {
        return $this->IDVService->createSession($sessionSpecification);
    }

    /**
     * Retrieves the state of a previously created Yoti Doc Scan session.
     *
     * @param string $sessionId
     * @return GetSessionResult
     * @throws Exception\IDVException
     */
    public function getSession(string $sessionId): GetSessionResult
    {
        return $this->IDVService->retrieveSession($sessionId);
    }

    /**
     * Deletes a previously created Yoti Doc Scan session and all
     * of its related resources.
     *
     * @param string $sessionId
     * @throws Exception\IDVException
     */
    public function deleteSession(string $sessionId): void
    {
        $this->IDVService->deleteSession($sessionId);
    }

    /**
     * Retrieves media related to a Yoti Doc Scan session based
     * on the supplied media ID.
     *
     * @param string $sessionId
     * @param string $mediaId
     * @return Media|null
     * @throws Exception\IDVException
     */
    public function getMediaContent(string $sessionId, string $mediaId): ?Media
    {
        return $this->IDVService->getMediaContent($sessionId, $mediaId);
    }

    /**
     * Deletes media related to a Yoti Doc Scan session based
     * on the supplied media ID.
     *
     * @param string $sessionId
     * @param string $mediaId
     * @throws Exception\IDVException
     */
    public function deleteMediaContent(string $sessionId, string $mediaId): void
    {
        $this->IDVService->deleteMediaContent($sessionId, $mediaId);
    }

    /**
     * Gets a list of supported documents.
     *
     * @param bool $isStrictlyLatin
     * @return SupportedDocumentsResponse
     * @throws Exception\IDVException
     */
    public function getSupportedDocuments(bool $isStrictlyLatin = false): SupportedDocumentsResponse
    {
        return $this->IDVService->getSupportedDocuments($isStrictlyLatin);
    }

    /**
     * Creates a Face Capture resource, that will be linked using
     * the supplied requirement ID
     *
     * @param string $sessionId
     * @param CreateFaceCaptureResourcePayload $createFaceCaptureResourcePayload
     * @return Session\Retrieve\CreateFaceCaptureResourceResponse
     * @throws Exception\IDVException
     */
    public function createFaceCaptureResource(
        string $sessionId,
        CreateFaceCaptureResourcePayload $createFaceCaptureResourcePayload
    ): Session\Retrieve\CreateFaceCaptureResourceResponse {
        return $this->IDVService->createFaceCaptureResource($sessionId, $createFaceCaptureResourcePayload);
    }

    /**
     * Uploads an image to the specified Face Capture resource
     *
     * @param string $sessionId
     * @param string $resourceId
     * @param UploadFaceCaptureImagePayload $uploadFaceCaptureImagePayload
     * @throws Exception\IDVException
     */
    public function uploadFaceCaptureImage(
        string $sessionId,
        string $resourceId,
        UploadFaceCaptureImagePayload $uploadFaceCaptureImagePayload
    ): void {
        $this->IDVService->uploadFaceCaptureImage($sessionId, $resourceId, $uploadFaceCaptureImagePayload);
    }

    /**
     * Fetches the configuration for the given sessionID.
     *
     * @param string $sessionId
     * @return SessionConfigurationResponse
     * @throws Exception\IDVException
     */
    public function getSessionConfiguration(string $sessionId): SessionConfigurationResponse
    {
        return $this->IDVService->fetchSessionConfiguration($sessionId);
    }

    /**
     * Sets the IBV instructions for the given session
     *
     * @throws Exception\IDVException
     */
    public function putIbvInstructions(string $sessionId, Instructions $instructions): void
    {
        $this->IDVService->putIbvInstructions($sessionId, $instructions);
    }

    /**
     * Fetches any currently set instructions for an IBV session.
     *
     * @param string $sessionId
     * @return InstructionsResponse
     * @throws Exception\IDVException
     */
    public function getIbvInstructions(string $sessionId): InstructionsResponse
    {
        return $this->IDVService->getIbvInstructions($sessionId);
    }

    /**
     * Fetches the instructions PDF associated with an In-Branch Verification session.
     *
     * @param string $sessionId
     * @return Media
     * @throws Exception\IDVException
     */
    public function getIbvInstructionsPdf(string $sessionId): Media
    {
        return $this->IDVService->getIbvInstructionsPdf($sessionId);
    }

    /**
     * Fetches the associated instructions contact profile for the given In-Branch Verification session
     *
     * @param string $sessionId
     * @return ContactProfileResponse
     * @throws Exception\IDVException
     */
    public function fetchInstructionsContactProfile(string $sessionId): ContactProfileResponse
    {
        return $this->IDVService->fetchInstructionsContactProfile($sessionId);
    }

    /**
     * Triggers an email notification for the IBV instructions at-home flow.
     * This will be one of:
     *  - an email sent directly to the end user, using the email provided in the ContactProfile
     *  - if requested, a backend notification using the configured notification endpoint
     *
     * @throws Exception\IDVException
     */
    public function triggerIbvEmailNotification(string $sessionId): void
    {
        $this->IDVService->triggerIbvEmailNotification($sessionId);
    }
}
