<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtraData.proto

namespace Yoti\Protobuf\Sharepubapi\GPBMetadata;

class ExtraData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Yoti\Protobuf\Sharepubapi\GPBMetadata\DataEntry::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ç
ExtraData.protosharepubapi_v1"4
	ExtraData\'
list (2.sharepubapi_v1.DataEntryBå
$com.yoti.api.client.spi.remote.protoBExtraDataProtoZ0github.com/getyoti/yoti-go-sdk/v3/yotiprotoshareªYoti.Auth.ProtoBuf.ShareÊYoti\\Protobuf\\Sharepubapiâ%Yoti\\Protobuf\\Sharepubapi\\GPBMetadataêYoti::Protobuf::Sharepubapibproto3'
        , true);

        static::$is_initialized = true;
    }
}

