<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IssuingAttributes.proto

namespace Yoti\Protobuf\Sharepubapi\GPBMetadata;

class IssuingAttributes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
˜
IssuingAttributes.protosharepubapi_v1"Y
IssuingAttributes
expiry_date (	/
definitions (2.sharepubapi_v1.Definition"

Definition
name (	Bí
$com.yoti.api.client.spi.remote.protoBIssuingAttributesProtoZ0github.com/getyoti/yoti-go-sdk/v3/yotiprotoshareªYoti.Auth.ProtoBuf.ShareÊYoti\\Protobuf\\Sharepubapiâ%Yoti\\Protobuf\\Sharepubapi\\GPBMetadataêYoti::Protobuf::Sharepubapibproto3'
        , true);

        static::$is_initialized = true;
    }
}

