<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdPartyAttribute.proto

namespace Yoti\Protobuf\Sharepubapi\GPBMetadata;

class ThirdPartyAttribute
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Yoti\Protobuf\Sharepubapi\GPBMetadata\IssuingAttributes::initOnce();
        $pool->internalAddGeneratedFile(
            '
“
ThirdPartyAttribute.protosharepubapi_v1"l
ThirdPartyAttribute
issuance_token (=
issuing_attributes (2!.sharepubapi_v1.IssuingAttributesBï
$com.yoti.api.client.spi.remote.protoBThirdPartyAttributeProtoZ0github.com/getyoti/yoti-go-sdk/v3/yotiprotoshareªYoti.Auth.ProtoBuf.ShareÊYoti\\Protobuf\\Sharepubapiâ%Yoti\\Protobuf\\Sharepubapi\\GPBMetadataêYoti::Protobuf::Sharepubapibproto3'
        , true);

        static::$is_initialized = true;
    }
}

