<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto

namespace Attrpubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.AttributeList</code>
 */
class AttributeList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    private $attributes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Attrpubapi\Attribute[]|\Google\Protobuf\Internal\RepeatedField $attributes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     * @param \Attrpubapi\Attribute[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Attrpubapi\Attribute::class);
        $this->attributes = $arr;

        return $this;
    }

}

