<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Attribute.proto

namespace Attrpubapi;

if (false) {
    /**
     * This class is deprecated. Use Attrpubapi\MultiValue\Value instead.
     * @deprecated
     */
    class MultiValue_Value {}
}
class_exists(MultiValue\Value::class);
@trigger_error('Attrpubapi\MultiValue_Value is deprecated and will be removed in the next major release. Use Attrpubapi\MultiValue\Value instead', E_USER_DEPRECATED);

