<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Attribute.proto

namespace Yoti\Protobuf\Attrpubapi\MultiValue;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.MultiValue.Value</code>
 */
class Value extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.attrpubapi_v1.ContentType content_type = 1;</code>
     */
    private $content_type = 0;
    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    private $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $content_type
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\Attribute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.attrpubapi_v1.ContentType content_type = 1;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Generated from protobuf field <code>.attrpubapi_v1.ContentType content_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkEnum($var, \Yoti\Protobuf\Attrpubapi\ContentType::class);
        $this->content_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Value::class, \Yoti\Protobuf\Attrpubapi\MultiValue_Value::class);

