<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataEntry.proto

namespace Yoti\Protobuf\Sharepubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sharepubapi_v1.DataEntry</code>
 */
class DataEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.sharepubapi_v1.DataEntry.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    private $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $value
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Sharepubapi\GPBMetadata\DataEntry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.sharepubapi_v1.DataEntry.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.sharepubapi_v1.DataEntry.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Yoti\Protobuf\Sharepubapi\DataEntry_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

}

