<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtraData.proto

namespace Yoti\Protobuf\Sharepubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sharepubapi_v1.ExtraData</code>
 */
class ExtraData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     */
    private $list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yoti\Protobuf\Sharepubapi\DataEntry[]|\Google\Protobuf\Internal\RepeatedField $list
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Sharepubapi\GPBMetadata\ExtraData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>repeated .sharepubapi_v1.DataEntry list = 1;</code>
     * @param \Yoti\Protobuf\Sharepubapi\DataEntry[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yoti\Protobuf\Sharepubapi\DataEntry::class);
        $this->list = $arr;

        return $this;
    }

}

