<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdPartyAttribute.proto

namespace Yoti\Protobuf\Sharepubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sharepubapi_v1.ThirdPartyAttribute</code>
 */
class ThirdPartyAttribute extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes issuance_token = 1;</code>
     */
    private $issuance_token = '';
    /**
     * Generated from protobuf field <code>.sharepubapi_v1.IssuingAttributes issuing_attributes = 2;</code>
     */
    private $issuing_attributes = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $issuance_token
     *     @type \Yoti\Protobuf\Sharepubapi\IssuingAttributes $issuing_attributes
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Sharepubapi\GPBMetadata\ThirdPartyAttribute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes issuance_token = 1;</code>
     * @return string
     */
    public function getIssuanceToken()
    {
        return $this->issuance_token;
    }

    /**
     * Generated from protobuf field <code>bytes issuance_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIssuanceToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->issuance_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.sharepubapi_v1.IssuingAttributes issuing_attributes = 2;</code>
     * @return \Yoti\Protobuf\Sharepubapi\IssuingAttributes
     */
    public function getIssuingAttributes()
    {
        return $this->issuing_attributes;
    }

    /**
     * Generated from protobuf field <code>.sharepubapi_v1.IssuingAttributes issuing_attributes = 2;</code>
     * @param \Yoti\Protobuf\Sharepubapi\IssuingAttributes $var
     * @return $this
     */
    public function setIssuingAttributes($var)
    {
        GPBUtil::checkMessage($var, \Yoti\Protobuf\Sharepubapi\IssuingAttributes::class);
        $this->issuing_attributes = $var;

        return $this;
    }

}

