<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtraData.proto

namespace Yoti\Sharepubapi\GPBMetadata;

class ExtraData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Yoti\Sharepubapi\GPBMetadata\DataEntry::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91020a0f4578747261446174612e70726f746f120e7368617265707562" .
            "6170695f763122340a0945787472614461746112270a046c697374180120" .
            "03280b32192e73686172657075626170695f76312e44617461456e747279" .
            "42af010a24636f6d2e796f74692e6170692e636c69656e742e7370692e72" .
            "656d6f74652e70726f746f420e45787472614461746150726f746f5a0e79" .
            "6f746970726f746f7368617265aa0218596f74692e417574682e50726f74" .
            "6f4275662e5368617265ca0210596f74695c5368617265707562617069e2" .
            "021c596f74695c53686172657075626170695c4750424d65746164617461" .
            "ea0219596f74692e50726f746f6275662e53686172657075626170696206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

