<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataEntry.proto

namespace Sharepubapi;

if (false) {
    /**
     * This class is deprecated. Use Sharepubapi\DataEntry\Type instead.
     * @deprecated
     */
    class DataEntry_Type {}
}
class_exists(DataEntry\Type::class);
@trigger_error('Sharepubapi\DataEntry_Type is deprecated and will be removed in the next major release. Use Sharepubapi\DataEntry\Type instead', E_USER_DEPRECATED);

