<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentType.proto

namespace GPBMetadata;

class ContentType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1010a11436f6e74656e74547970652e70726f746f120d617474727075" .
            "626170695f76312a4f0a0b436f6e74656e7454797065120d0a09554e4445" .
            "46494e45441000120a0a06535452494e47100112080a044a504547100212" .
            "080a0444415445100312070a03504e47100412080a044a534f4e10054254" .
            "0a24636f6d2e796f74692e6170692e636c69656e742e7370692e72656d6f" .
            "74652e70726f746f4210436f6e74656e745479706550726f746f5a0d796f" .
            "746970726f746f61747472ca020a41747472707562617069620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

