<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EncryptedData.proto

namespace GPBMetadata;

class EncryptedData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a010a13456e63727970746564446174612e70726f746f120c636f6d70" .
            "75626170695f763122300a0d456e6372797074656444617461120a0a0269" .
            "7618012001280c12130a0b6369706865725f7465787418022001280c422b" .
            "0a15636f6d2e796f74692e636f6d7075626170695f76314212456e637279" .
            "707465644461746150726f746f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

