<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EncryptedData.proto

namespace GPBMetadata;

class EncryptedData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab3010a13456e63727970746564446174612e70726f746f120c636f6d70" .
            "75626170695f763122300a0d456e6372797074656444617461120a0a0269" .
            "7618012001280c12130a0b6369706865725f7465787418022001280c4254" .
            "0a24636f6d2e796f74692e6170692e636c69656e742e7370692e72656d6f" .
            "74652e70726f746f4212456e637279707465644461746150726f746f5a0c" .
            "796f746970726f746f636f6dca0209436f6d707562617069620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

