<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto

namespace GPBMetadata;

class ProtoList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Attribute::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab0020a0a4c6973742e70726f746f120d617474727075626170695f7631" .
            "22530a0e417474726962757465416e644964122b0a096174747269627574" .
            "6518012001280b32182e617474727075626170695f76312e417474726962" .
            "75746512140a0c6174747269627574655f696418022001280c22520a1241" .
            "7474726962757465416e6449644c697374123c0a15617474726962757465" .
            "5f616e645f69645f6c69737418012003280b321d2e617474727075626170" .
            "695f76312e417474726962757465416e644964223d0a0d41747472696275" .
            "74654c697374122c0a0a6174747269627574657318012003280b32182e61" .
            "7474727075626170695f76312e41747472696275746542230a16636f6d2e" .
            "796f74692e617474727075626170695f763142094174747250726f746f62" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

