<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Signing.proto

namespace GPBMetadata;

class Signing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ContentType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5020a0d5369676e696e672e70726f746f120d61747472707562617069" .
            "5f763122aa010a104174747269627574655369676e696e67120c0a046e61" .
            "6d65180120012809120d0a0576616c756518022001280c12300a0c636f6e" .
            "74656e745f7479706518032001280e321a2e617474727075626170695f76" .
            "312e436f6e74656e7454797065121a0a1261727469666163745f7369676e" .
            "617475726518042001280c12100a087375625f7479706518052001280912" .
            "190a117369676e65645f74696d655f7374616d7018062001280c42500a24" .
            "636f6d2e796f74692e6170692e636c69656e742e7370692e72656d6f7465" .
            "2e70726f746f420c5369676e696e6750726f746f5a0d796f746970726f74" .
            "6f61747472ca020a41747472707562617069620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

