<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignedTimestamp.proto

namespace GPBMetadata;

class SignedTimestamp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3020a155369676e656454696d657374616d702e70726f746f120c636f" .
            "6d7075626170695f7631229b010a0f5369676e656454696d657374616d70" .
            "120f0a0776657273696f6e18012001280512110a0974696d657374616d70" .
            "18022001280412160a0e6d6573736167655f64696765737418032001280c" .
            "12140a0c636861696e5f64696765737418042001280c121a0a1263686169" .
            "6e5f6469676573745f736b69703118052001280c121a0a12636861696e5f" .
            "6469676573745f736b69703218062001280c42560a24636f6d2e796f7469" .
            "2e6170692e636c69656e742e7370692e72656d6f74652e70726f746f4214" .
            "5369676e656454696d657374616d7050726f746f5a0c796f746970726f74" .
            "6f636f6dca0209436f6d707562617069620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

