<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto

namespace Attrpubapi_v1;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.AttributeList</code>
 */
class AttributeList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     */
    private $attributes;

    public function __construct() {
        \GPBMetadata\ProtoList::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.Attribute attributes = 1;</code>
     * @param \Attrpubapi_v1\Attribute[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Attrpubapi_v1\Attribute::class);
        $this->attributes = $arr;

        return $this;
    }

}

