<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto

namespace Attrpubapi_v1;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.AttributeAndIdList</code>
 */
class AttributeAndIdList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    private $attribute_and_id_list;

    public function __construct() {
        \GPBMetadata\ProtoList::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributeAndIdList()
    {
        return $this->attribute_and_id_list;
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     * @param \Attrpubapi_v1\AttributeAndId[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributeAndIdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Attrpubapi_v1\AttributeAndId::class);
        $this->attribute_and_id_list = $arr;

        return $this;
    }

}

