<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Attribute.proto
 */


namespace attrpubapi_v1;

/**
 * Protobuf enum : attrpubapi_v1.ContentType
 */
class ContentType extends \Protobuf\Enum
{

    /**
     * UNDEFINED = 0
     */
    const UNDEFINED_VALUE = 0;

    /**
     * STRING = 1
     */
    const STRING_VALUE = 1;

    /**
     * JPEG = 2
     */
    const JPEG_VALUE = 2;

    /**
     * DATE = 3
     */
    const DATE_VALUE = 3;

    /**
     * PNG = 4
     */
    const PNG_VALUE = 4;

    /**
     * @var \attrpubapi_v1\ContentType
     */
    protected static $UNDEFINED = null;

    /**
     * @var \attrpubapi_v1\ContentType
     */
    protected static $STRING = null;

    /**
     * @var \attrpubapi_v1\ContentType
     */
    protected static $JPEG = null;

    /**
     * @var \attrpubapi_v1\ContentType
     */
    protected static $DATE = null;

    /**
     * @var \attrpubapi_v1\ContentType
     */
    protected static $PNG = null;

    /**
     * @return \attrpubapi_v1\ContentType
     */
    public static function UNDEFINED()
    {
        if (self::$UNDEFINED !== null) {
            return self::$UNDEFINED;
        }

        return self::$UNDEFINED = new self('UNDEFINED', self::UNDEFINED_VALUE);
    }

    /**
     * @return \attrpubapi_v1\ContentType
     */
    public static function STRING()
    {
        if (self::$STRING !== null) {
            return self::$STRING;
        }

        return self::$STRING = new self('STRING', self::STRING_VALUE);
    }

    /**
     * @return \attrpubapi_v1\ContentType
     */
    public static function JPEG()
    {
        if (self::$JPEG !== null) {
            return self::$JPEG;
        }

        return self::$JPEG = new self('JPEG', self::JPEG_VALUE);
    }

    /**
     * @return \attrpubapi_v1\ContentType
     */
    public static function DATE()
    {
        if (self::$DATE !== null) {
            return self::$DATE;
        }

        return self::$DATE = new self('DATE', self::DATE_VALUE);
    }

    /**
     * @return \attrpubapi_v1\ContentType
     */
    public static function PNG()
    {
        if (self::$PNG !== null) {
            return self::$PNG;
        }

        return self::$PNG = new self('PNG', self::PNG_VALUE);
    }

    /**
     * @param int $value
     * @return \attrpubapi_v1\ContentType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::UNDEFINED();
            case 1: return self::STRING();
            case 2: return self::JPEG();
            case 3: return self::DATE();
            case 4: return self::PNG();
            default: return null;
        }
    }


}

