<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Attribute.proto

namespace Attrpubapi_v1;

/**
 * ContentType indicates how to interpret the ‘Value’ field of an Attribute.
 *
 * Protobuf enum <code>Attrpubapi_v1\ContentType</code>
 */
class ContentType
{
    /**
     * UNDEFINED should not be seen, and is used as an error placeholder
     * value.
     *
     * Generated from protobuf enum <code>UNDEFINED = 0;</code>
     */
    const UNDEFINED = 0;
    /**
     * STRING means the value is UTF-8 encoded text.
     *
     * Generated from protobuf enum <code>STRING = 1;</code>
     */
    const STRING = 1;
    /**
     * JPEG indicates a standard .jpeg image.
     *
     * Generated from protobuf enum <code>JPEG = 2;</code>
     */
    const JPEG = 2;
    /**
     * Date as string in RFC3339 format (YYYY-MM-DD).
     *
     * Generated from protobuf enum <code>DATE = 3;</code>
     */
    const DATE = 3;
    /**
     * PNG indicates a standard .png image.
     *
     * Generated from protobuf enum <code>PNG = 4;</code>
     */
    const PNG = 4;

    /**
     * JSON string
     *
     * Generated from protobuf enum <code>JSON = 5;</code>
     */
    const JSON = 5;
}

