<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentType.proto

namespace Yoti\Protobuf\Attrpubapi\GPBMetadata;

class ContentType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adb020a11436f6e74656e74547970652e70726f746f120d617474727075" .
            "626170695f76312a690a0b436f6e74656e7454797065120d0a09554e4445" .
            "46494e45441000120a0a06535452494e47100112080a044a504547100212" .
            "080a0444415445100312070a03504e47100412080a044a534f4e1005120f" .
            "0a0b4d554c54495f56414c5545100612070a03494e54100742c3010a2463" .
            "6f6d2e796f74692e6170692e636c69656e742e7370692e72656d6f74652e" .
            "70726f746f4210436f6e74656e745479706550726f746f5a0d796f746970" .
            "726f746f61747472aa021c596f74692e417574682e50726f746f4275662e" .
            "417474726962757465ca0218596f74695c50726f746f6275665c41747472" .
            "707562617069e20224596f74695c50726f746f6275665c41747472707562" .
            "6170695c4750424d65746164617461ea0218596f74692e50726f746f6275" .
            "662e41747472707562617069620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

