<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto

namespace Yoti\Protobuf\Attrpubapi\GPBMetadata;

class PBList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\Attribute::initOnce();
        $pool->internalAddGeneratedFile(
            '
÷

List.protoattrpubapi_v1"S
AttributeAndId+
	attribute (2.attrpubapi_v1.Attribute
attribute_id ("R
AttributeAndIdList<
attribute_and_id_list (2.attrpubapi_v1.AttributeAndId"=
AttributeList,

attributes (2.attrpubapi_v1.AttributeBé
$com.yoti.api.client.spi.remote.protoBAttributeListProtoZ/github.com/getyoti/yoti-go-sdk/v3/yotiprotoattrªYoti.Auth.ProtoBuf.AttributeÊYoti\\Protobuf\\Attrpubapiâ$Yoti\\Protobuf\\Attrpubapi\\GPBMetadataêYoti::Protobuf::Attrpubapibproto3'
        , true);

        static::$is_initialized = true;
    }
}

