<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Signing.proto

namespace Yoti\Protobuf\Attrpubapi\GPBMetadata;

class Signing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\ContentType::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ô
Signing.protoattrpubapi_v1"Å
AttributeSigning
name (	
value (0
content_type (2.attrpubapi_v1.ContentType
artifact_signature (
sub_type (	
signed_time_stamp (
associated_source (	Bã
$com.yoti.api.client.spi.remote.protoBSigningProtoZ/github.com/getyoti/yoti-go-sdk/v3/yotiprotoattrªYoti.Auth.ProtoBuf.AttributeÊYoti\\Protobuf\\Attrpubapiâ$Yoti\\Protobuf\\Attrpubapi\\GPBMetadataêYoti::Protobuf::Attrpubapibproto3'
        , true);

        static::$is_initialized = true;
    }
}

