<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Signing.proto

namespace Yoti\Protobuf\Attrpubapi\GPBMetadata;

class Signing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\ContentType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95030a0d5369676e696e672e70726f746f120d61747472707562617069" .
            "5f763122aa010a104174747269627574655369676e696e67120c0a046e61" .
            "6d65180120012809120d0a0576616c756518022001280c12300a0c636f6e" .
            "74656e745f7479706518032001280e321a2e617474727075626170695f76" .
            "312e436f6e74656e7454797065121a0a1261727469666163745f7369676e" .
            "617475726518042001280c12100a087375625f7479706518052001280912" .
            "190a117369676e65645f74696d655f7374616d7018062001280c42bf010a" .
            "24636f6d2e796f74692e6170692e636c69656e742e7370692e72656d6f74" .
            "652e70726f746f420c5369676e696e6750726f746f5a0d796f746970726f" .
            "746f61747472aa021c596f74692e417574682e50726f746f4275662e4174" .
            "74726962757465ca0218596f74695c50726f746f6275665c417474727075" .
            "62617069e20224596f74695c50726f746f6275665c417474727075626170" .
            "695c4750424d65746164617461ea0218596f74692e50726f746f6275662e" .
            "41747472707562617069620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

