<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EncryptedData.proto

namespace Yoti\Protobuf\Compubapi\GPBMetadata;

class EncryptedData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Â
EncryptedData.protocompubapi_v1"0
EncryptedData

iv (
cipher_text (Bâ
$com.yoti.api.client.spi.remote.protoBEncryptedDataProtoZ.github.com/getyoti/yoti-go-sdk/v3/yotiprotocomªYoti.Auth.ProtoBuf.CommonÊYoti\\Protobuf\\Compubapiâ#Yoti\\Protobuf\\Compubapi\\GPBMetadataêYoti::Protobuf::Compubapibproto3'
        , true);

        static::$is_initialized = true;
    }
}

