<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignedTimestamp.proto

namespace Yoti\Protobuf\Compubapi\GPBMetadata;

class SignedTimestamp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
²
SignedTimestamp.protocompubapi_v1"›
SignedTimestamp
version (
	timestamp (
message_digest (
chain_digest (
chain_digest_skip1 (
chain_digest_skip2 (Bä
$com.yoti.api.client.spi.remote.protoBSignedTimestampProtoZ.github.com/getyoti/yoti-go-sdk/v3/yotiprotocomªYoti.Auth.ProtoBuf.CommonÊYoti\\Protobuf\\Compubapiâ#Yoti\\Protobuf\\Compubapi\\GPBMetadataêYoti::Protobuf::Compubapibproto3'
        , true);

        static::$is_initialized = true;
    }
}

