<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignedTimestamp.proto

namespace Yoti\Protobuf\Compubapi\GPBMetadata;

class SignedTimestamp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e030a155369676e656454696d657374616d702e70726f746f120c636f" .
            "6d7075626170695f7631229b010a0f5369676e656454696d657374616d70" .
            "120f0a0776657273696f6e18012001280512110a0974696d657374616d70" .
            "18022001280412160a0e6d6573736167655f64696765737418032001280c" .
            "12140a0c636861696e5f64696765737418042001280c121a0a1263686169" .
            "6e5f6469676573745f736b69703118052001280c121a0a12636861696e5f" .
            "6469676573745f736b69703218062001280c42c0010a24636f6d2e796f74" .
            "692e6170692e636c69656e742e7370692e72656d6f74652e70726f746f42" .
            "145369676e656454696d657374616d7050726f746f5a0c796f746970726f" .
            "746f636f6daa0219596f74692e417574682e50726f746f4275662e436f6d" .
            "6d6f6eca0217596f74695c50726f746f6275665c436f6d707562617069e2" .
            "0223596f74695c50726f746f6275665c436f6d7075626170695c4750424d" .
            "65746164617461ea0217596f74692e50726f746f6275662e436f6d707562" .
            "617069620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

