<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Attribute.proto

namespace Yoti\Protobuf\Attrpubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.Anchor</code>
 */
class Anchor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes artifact_link = 1;</code>
     */
    private $artifact_link = '';
    /**
     * Generated from protobuf field <code>repeated bytes origin_server_certs = 2;</code>
     */
    private $origin_server_certs;
    /**
     * Generated from protobuf field <code>bytes artifact_signature = 3;</code>
     */
    private $artifact_signature = '';
    /**
     * Generated from protobuf field <code>string sub_type = 4;</code>
     */
    private $sub_type = '';
    /**
     * Generated from protobuf field <code>bytes signature = 5;</code>
     */
    private $signature = '';
    /**
     * Generated from protobuf field <code>bytes signed_time_stamp = 6;</code>
     */
    private $signed_time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $artifact_link
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $origin_server_certs
     *     @type string $artifact_signature
     *     @type string $sub_type
     *     @type string $signature
     *     @type string $signed_time_stamp
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\Attribute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes artifact_link = 1;</code>
     * @return string
     */
    public function getArtifactLink()
    {
        return $this->artifact_link;
    }

    /**
     * Generated from protobuf field <code>bytes artifact_link = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setArtifactLink($var)
    {
        GPBUtil::checkString($var, False);
        $this->artifact_link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes origin_server_certs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOriginServerCerts()
    {
        return $this->origin_server_certs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes origin_server_certs = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOriginServerCerts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->origin_server_certs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes artifact_signature = 3;</code>
     * @return string
     */
    public function getArtifactSignature()
    {
        return $this->artifact_signature;
    }

    /**
     * Generated from protobuf field <code>bytes artifact_signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setArtifactSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->artifact_signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sub_type = 4;</code>
     * @return string
     */
    public function getSubType()
    {
        return $this->sub_type;
    }

    /**
     * Generated from protobuf field <code>string sub_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubType($var)
    {
        GPBUtil::checkString($var, True);
        $this->sub_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 5;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signed_time_stamp = 6;</code>
     * @return string
     */
    public function getSignedTimeStamp()
    {
        return $this->signed_time_stamp;
    }

    /**
     * Generated from protobuf field <code>bytes signed_time_stamp = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSignedTimeStamp($var)
    {
        GPBUtil::checkString($var, False);
        $this->signed_time_stamp = $var;

        return $this;
    }

}

