<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto

namespace Yoti\Protobuf\Attrpubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.AttributeAndId</code>
 */
class AttributeAndId extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.attrpubapi_v1.Attribute attribute = 1;</code>
     */
    private $attribute = null;
    /**
     * Generated from protobuf field <code>bytes attribute_id = 2;</code>
     */
    private $attribute_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yoti\Protobuf\Attrpubapi\Attribute $attribute
     *     @type string $attribute_id
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\PBList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.attrpubapi_v1.Attribute attribute = 1;</code>
     * @return \Yoti\Protobuf\Attrpubapi\Attribute
     */
    public function getAttribute()
    {
        return $this->attribute;
    }

    /**
     * Generated from protobuf field <code>.attrpubapi_v1.Attribute attribute = 1;</code>
     * @param \Yoti\Protobuf\Attrpubapi\Attribute $var
     * @return $this
     */
    public function setAttribute($var)
    {
        GPBUtil::checkMessage($var, \Yoti\Protobuf\Attrpubapi\Attribute::class);
        $this->attribute = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes attribute_id = 2;</code>
     * @return string
     */
    public function getAttributeId()
    {
        return $this->attribute_id;
    }

    /**
     * Generated from protobuf field <code>bytes attribute_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAttributeId($var)
    {
        GPBUtil::checkString($var, False);
        $this->attribute_id = $var;

        return $this;
    }

}

