<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto

namespace Yoti\Protobuf\Attrpubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.AttributeAndIdList</code>
 */
class AttributeAndIdList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     */
    private $attribute_and_id_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yoti\Protobuf\Attrpubapi\AttributeAndId[]|\Google\Protobuf\Internal\RepeatedField $attribute_and_id_list
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\PBList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributeAndIdList()
    {
        return $this->attribute_and_id_list;
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.AttributeAndId attribute_and_id_list = 1;</code>
     * @param \Yoti\Protobuf\Attrpubapi\AttributeAndId[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributeAndIdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yoti\Protobuf\Attrpubapi\AttributeAndId::class);
        $this->attribute_and_id_list = $arr;

        return $this;
    }

}

