<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Signing.proto

namespace Yoti\Protobuf\Attrpubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.AttributeSigning</code>
 */
class AttributeSigning extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    private $value = '';
    /**
     * Generated from protobuf field <code>.attrpubapi_v1.ContentType content_type = 3;</code>
     */
    private $content_type = 0;
    /**
     * Generated from protobuf field <code>bytes artifact_signature = 4;</code>
     */
    private $artifact_signature = '';
    /**
     * Generated from protobuf field <code>string sub_type = 5;</code>
     */
    private $sub_type = '';
    /**
     * Generated from protobuf field <code>bytes signed_time_stamp = 6;</code>
     */
    private $signed_time_stamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $value
     *     @type int $content_type
     *     @type string $artifact_signature
     *     @type string $sub_type
     *     @type string $signed_time_stamp
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\Signing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.attrpubapi_v1.ContentType content_type = 3;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Generated from protobuf field <code>.attrpubapi_v1.ContentType content_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkEnum($var, \Yoti\Protobuf\Attrpubapi\ContentType::class);
        $this->content_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes artifact_signature = 4;</code>
     * @return string
     */
    public function getArtifactSignature()
    {
        return $this->artifact_signature;
    }

    /**
     * Generated from protobuf field <code>bytes artifact_signature = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setArtifactSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->artifact_signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sub_type = 5;</code>
     * @return string
     */
    public function getSubType()
    {
        return $this->sub_type;
    }

    /**
     * Generated from protobuf field <code>string sub_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSubType($var)
    {
        GPBUtil::checkString($var, True);
        $this->sub_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signed_time_stamp = 6;</code>
     * @return string
     */
    public function getSignedTimeStamp()
    {
        return $this->signed_time_stamp;
    }

    /**
     * Generated from protobuf field <code>bytes signed_time_stamp = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSignedTimeStamp($var)
    {
        GPBUtil::checkString($var, False);
        $this->signed_time_stamp = $var;

        return $this;
    }

}

