<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentType.proto

namespace Yoti\Protobuf\Attrpubapi;

/**
 * Protobuf type <code>attrpubapi_v1.ContentType</code>
 */
class ContentType
{
    /**
     * Generated from protobuf enum <code>UNDEFINED = 0;</code>
     */
    const UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>STRING = 1;</code>
     */
    const STRING = 1;
    /**
     * Generated from protobuf enum <code>JPEG = 2;</code>
     */
    const JPEG = 2;
    /**
     * Generated from protobuf enum <code>DATE = 3;</code>
     */
    const DATE = 3;
    /**
     * Generated from protobuf enum <code>PNG = 4;</code>
     */
    const PNG = 4;
    /**
     * Generated from protobuf enum <code>JSON = 5;</code>
     */
    const JSON = 5;
    /**
     * Generated from protobuf enum <code>MULTI_VALUE = 6;</code>
     */
    const MULTI_VALUE = 6;
    /**
     * Generated from protobuf enum <code>INT = 7;</code>
     */
    const INT = 7;
}

