<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Attribute.proto

namespace Yoti\Protobuf\Attrpubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.Metadata</code>
 */
class Metadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string superseded_time_stamp = 1;</code>
     */
    protected $superseded_time_stamp = '';
    /**
     * Generated from protobuf field <code>bool deletable = 2;</code>
     */
    protected $deletable = false;
    /**
     * Generated from protobuf field <code>bytes receipt_id = 3;</code>
     */
    protected $receipt_id = '';
    /**
     * Generated from protobuf field <code>bool revoked = 4;</code>
     */
    protected $revoked = false;
    /**
     * Generated from protobuf field <code>bool locked = 5;</code>
     */
    protected $locked = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $superseded_time_stamp
     *     @type bool $deletable
     *     @type string $receipt_id
     *     @type bool $revoked
     *     @type bool $locked
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\Attribute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string superseded_time_stamp = 1;</code>
     * @return string
     */
    public function getSupersededTimeStamp()
    {
        return $this->superseded_time_stamp;
    }

    /**
     * Generated from protobuf field <code>string superseded_time_stamp = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSupersededTimeStamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->superseded_time_stamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool deletable = 2;</code>
     * @return bool
     */
    public function getDeletable()
    {
        return $this->deletable;
    }

    /**
     * Generated from protobuf field <code>bool deletable = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeletable($var)
    {
        GPBUtil::checkBool($var);
        $this->deletable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes receipt_id = 3;</code>
     * @return string
     */
    public function getReceiptId()
    {
        return $this->receipt_id;
    }

    /**
     * Generated from protobuf field <code>bytes receipt_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiptId($var)
    {
        GPBUtil::checkString($var, False);
        $this->receipt_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool revoked = 4;</code>
     * @return bool
     */
    public function getRevoked()
    {
        return $this->revoked;
    }

    /**
     * Generated from protobuf field <code>bool revoked = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRevoked($var)
    {
        GPBUtil::checkBool($var);
        $this->revoked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool locked = 5;</code>
     * @return bool
     */
    public function getLocked()
    {
        return $this->locked;
    }

    /**
     * Generated from protobuf field <code>bool locked = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->locked = $var;

        return $this;
    }

}

