<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Attribute.proto

namespace Yoti\Protobuf\Attrpubapi;

if (false) {
    /**
     * This class is deprecated. Use Yoti\Protobuf\Attrpubapi\MultiValue\Value instead.
     * @deprecated
     */
    class MultiValue_Value {}
}
class_exists(MultiValue\Value::class);
@trigger_error('Yoti\Protobuf\Attrpubapi\MultiValue_Value is deprecated and will be removed in the next major release. Use Yoti\Protobuf\Attrpubapi\MultiValue\Value instead', E_USER_DEPRECATED);

