<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Attribute.proto

namespace Yoti\Protobuf\Attrpubapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>attrpubapi_v1.MultiValue</code>
 */
class MultiValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.MultiValue.Value values = 1;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Yoti\Protobuf\Attrpubapi\MultiValue\Value[]|\Google\Protobuf\Internal\RepeatedField $values
     * }
     */
    public function __construct($data = NULL) {
        \Yoti\Protobuf\Attrpubapi\GPBMetadata\Attribute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.MultiValue.Value values = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .attrpubapi_v1.MultiValue.Value values = 1;</code>
     * @param \Yoti\Protobuf\Attrpubapi\MultiValue\Value[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Yoti\Protobuf\Attrpubapi\MultiValue\Value::class);
        $this->values = $arr;

        return $this;
    }

}

