<?php

namespace Yoti\DocScan;

class Constants
{
    public const ID_DOCUMENT_AUTHENTICITY = 'ID_DOCUMENT_AUTHENTICITY';
    public const ID_DOCUMENT_COMPARISON = 'ID_DOCUMENT_COMPARISON';
    public const ID_DOCUMENT_TEXT_DATA_CHECK = 'ID_DOCUMENT_TEXT_DATA_CHECK';
    public const SUPPLEMENTARY_DOCUMENT_TEXT_DATA_CHECK = 'SUPPLEMENTARY_DOCUMENT_TEXT_DATA_CHECK';
    public const ID_DOCUMENT_FACE_MATCH = 'ID_DOCUMENT_FACE_MATCH';
    public const LIVENESS = 'LIVENESS';

    public const ID_DOCUMENT_TEXT_DATA_EXTRACTION = 'ID_DOCUMENT_TEXT_DATA_EXTRACTION';
    public const SUPPLEMENTARY_DOCUMENT_TEXT_DATA_EXTRACTION = 'SUPPLEMENTARY_DOCUMENT_TEXT_DATA_EXTRACTION';

    public const ID_DOCUMENT = 'ID_DOCUMENT';
    public const SUPPLEMENTARY_DOCUMENT = 'SUPPLEMENTARY_DOCUMENT';
    public const ORTHOGONAL_RESTRICTIONS = 'ORTHOGONAL_RESTRICTIONS';
    public const DOCUMENT_RESTRICTIONS = 'DOCUMENT_RESTRICTIONS';
    public const INCLUSION_WHITELIST = 'WHITELIST';
    public const INCLUSION_BLACKLIST = 'BLACKLIST';

    public const ALWAYS = 'ALWAYS';
    public const FALLBACK = 'FALLBACK';
    public const NEVER = 'NEVER';
}
